<?php

/**
 * @file
 * Code for the cwrc_baseline feature.
 */

include_once 'cwrc_baseline.features.inc';

/* Hooks. */

/**
 * Implements hook_menu().
 */
function cwrc_baseline_menu() {
  $items = array();
  $items['front'] = array(
    'title' => 'Front Page',
    'page callback' => 'cwrc_baseline_front',
    // No access restriction because anyone should be able to access the front
    // page of the site.
    'access callback' => TRUE,
  );
  $items['notfound'] = array(
    'title' => 'Page not found',
    'page callback' => 'cwrc_baseline_404',
    // No access restriction because anyone should be able to get a 404 error.
    'access callback' => TRUE,
  );
  return $items;
}

/* Menu callbacks. */

/**
 * Page callback: Display a blank front page.
 */
function cwrc_baseline_front() {
  return '';
}

/**
 * Page callback: Display a simple message for a 404 page.
 */
function cwrc_baseline_404() {
  return t("The requested page could not be found!");
}
