<?php

/**
 * @file
 * Code for the Borealis Block Wrappers module.
 */

/* Hooks. */

/**
 * Implements hook_module_implements_alter().
 */
function borealis_block_wrappers_module_implements_alter(&$implementations, $hook) {
  // Implement this hook_form_alter after any others.
  if (in_array($hook, array('form_alter'))) {
    $module = 'borealis_block_wrappers';
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations[$module] = $group;
  }
}

/**
 * Implements hook_form_alter().
 */
function borealis_block_wrappers_form_alter(&$form, &$form_state, $form_id) {
  // Only want this showing up on Block Add and Configure pages.
  if ($form_id == 'block_admin_configure' || $form_id == 'block_add_block_form') {
    if (user_access('administer block semantics')) {
      $form['semantics']['wrapper']['#options']['zip'] = t('Default');

      // Switch out Borealis validation for our validation.
      if (($key = array_search('borealis_sb_admin_validate', $form['#validate'])) !== FALSE) {
        unset($form['#validate'][$key]);
      }
      $form['#validate'][] = 'borealis_block_wrappers_admin_validate';
    }
  }
}

/* Form handlers. */

/**
 * Form validation handler for block_admin_configure and block_add_block_form.
 *
 * @see borealis_block_wrappers_form_alter()
 */
function borealis_block_wrappers_admin_validate($form, &$form_state) {
  $wrapper_value = $form_state['complete form']['semantics']['wrapper']['#value'];
  $wrapper_valid = array(
    'zip',
    'div',
    'article',
    'aside',
    'nav',
    'span',
    'none',
  );
  if (!in_array($wrapper_value, $wrapper_valid)) {
    form_set_error('wrapper', t('What did you do!'));
  }
}

/* Theme functions. */

/**
 * Implements hook_preprocess_HOOK() for block.tpl.php.
 */
function borealis_block_wrappers_preprocess_block(&$variables) {
  // Display Suite has problems with this approach, semantics must be loaded.
  if (!isset($variables['block']->semantics)) {
    $variables['block']->semantics = borealis_sb_get_wrapper($variables['block']->module, $variables['block']->delta);
  }

  // Add additional template suggestions for compatibilty with Semantic Blocks
  // module.
  $markup = check_plain($variables['block']->semantics);
  $module = check_plain($variables['block']->module);
  $delta = strtr($variables['block']->delta, '-', '_');
  $variables['theme_hook_suggestions'][] = 'block__' . $markup . '__' . $module . '__' . $delta;
}
