<?php
/**
 * @file
 * Handles the creation/display of islandora:markupEditorCModel objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_markup_editor_menu() {
  $items['islandora/markupeditor/setup/%islandora_object'] = array(
    'title' => 'Markup Editor Setup',
    'page callback' => 'islandora_markup_editor_setup',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'includes/callbacks.inc',
    'access callback' => 'islandora_object_access_callback',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 3),
  );
  $items['islandora/markupeditor/save_data/%islandora_object'] = array(
    'title' => 'Save Data',
    'page callback' => 'islandora_markup_editor_savedata',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'includes/callbacks.inc',
    'access callback' => 'islandora_markup_editor_save_tei_access',
    'access arguments' => array(3),
  );
  return $items;
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_markup_editor_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_markup_editor');
  // Markup Editor Content Model.
  $markup_editor_model = $connection->repository->constructObject('islandora:markupEditorCModel');
  $markup_editor_model->owner = 'fedoraAdmin';
  $markup_editor_model->label = 'Islandora Markup Editor Content Model';
  $markup_editor_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $markup_editor_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_markup_editor_ds_composite_model.xml", FALSE);
  $markup_editor_model->ingestDatastream($datastream);
  // Markup Editor Collection.
  $markup_editor_collection = $connection->repository->constructObject('islandora:markup_editor_collection');
  $markup_editor_collection->owner = 'fedoraAdmin';
  $markup_editor_collection->label = 'Markup Editor Collection';
  $markup_editor_collection->models = 'islandora:collectionCModel';
  $markup_editor_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', variable_get('islandora_repository_pid', 'islandora:root'));
  // Collection Policy Datastream.
  $datastream = $markup_editor_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_markup_editor_collection_policy.xml", FALSE);
  $markup_editor_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $markup_editor_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $markup_editor_collection->ingestDatastream($datastream);
  // RDF Schema Content Model.
  $markup_editor_schema_content_model = $connection->repository->constructObject('islandora:markupeditorschemaCModel');
  $markup_editor_schema_content_model->owner = 'fedoraAdmin';
  $markup_editor_schema_content_model->label = 'Schema Content Model';
  $markup_editor_schema_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $markup_editor_schema_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_markup_editor_schema_ds_composite_model.xml", FALSE);
  $markup_editor_schema_content_model->ingestDatastream($datastream);
  // Schema Collection.
  $schema_collection = $connection->repository->constructObject('islandora:tei_schema_collection');
  $schema_collection->owner = 'fedoraAdmin';
  $schema_collection->label = 'Schema Collection';
  $schema_collection->models = 'islandora:collectionCModel';
  $schema_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $schema_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_markup_editor_schema_collection_policy.xml", FALSE);
  $schema_collection->ingestDatastream($datastream);

  // Ingest the basic schema types.
  $sample_schema = $connection->repository->constructObject('islandora:tei_sample_schema');
  $sample_schema->owner = 'fedoraAdmin';
  $sample_schema->label = 'CWRC_EMiC_TEI_Schema';
  $sample_schema->models = 'islandora:markupeditorschemaCModel';
  $sample_schema->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:tei_schema_collection');

  // Add the RDF (schema) datastream.
  $new_ds = $sample_schema->constructDatastream('RDF-SCHEMA', 'M');
  $new_ds->label = 'RDF-SCHEMA';
  $new_ds->mimetype = 'application/xml';
  $new_ds->setContentFromFile("$module_path/CWRC-Writer/src/schema/CWRC-TEIBasic.rng", FALSE);
  $sample_schema->ingestDatastream($new_ds);

  // Add the TEI (RDF) CSS datastream.
  $new_ds_css = $sample_schema->constructDatastream('RDF-CSS', 'M');
  $new_ds_css->label = 'RDF-CSS';
  $new_ds_css->mimetype = 'text/css';
  $new_ds_css->setContentFromFile("$module_path/CWRC-Writer/src/css/tei.css", FALSE);
  $sample_schema->ingestDatastream($new_ds_css);

  return array(
    'islandora_markup_editor' => array(
      'title' => 'Islandora markup editor',
      'objects' => array(
        $markup_editor_model,
        $markup_editor_collection,
        $markup_editor_schema_content_model,
        $schema_collection,
        $sample_schema,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_markup_editor_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_markup_editor');
  return array(
    'Markup Editor MODS form' => array(
      'form_file' => "$module_path/xml/islandora_markup_editor_form_mods.xml",
    ),
    'Schema MODS form' => array(
      'form_file' => "$module_path/xml/islandora_markup_editor_schema_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_markup_editor_islandora_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_markup_editor_mods_form' => array(
      'content_model' => 'islandora:markupEditorCModel',
      'form_name' => 'Markup Editor MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_markup_editor_schema_form_mods' => array(
      'content_model' => 'islandora:markupeditorschemaCModel',
      'form_name' => 'Schema MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_markup_editor_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_markup_editor' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-markup-editor',
      'pattern' => 'islandora_markup_editor__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_library().
 */
function islandora_markup_editor_library() {
  $module_path = drupal_get_path('module', 'islandora_markup_editor');
  $items = array();
  $items['cwrcwriter'] = array(
    'title' => t('CWRC-Writer Library'),
    'version' => '1.0',
    'js' => array(
      "$module_path/CWRC-Writer/src/js/config.js" => array(),
      "$module_path/CWRC-Writer/src/js/lib/require/require.js" => array(),
      "$module_path/CWRC-Writer/src/js/layout.js" => array(),
    ),
    'css' => array(
      "$module_path/CWRC-Writer/src/css/editor.css" => array(),
      "$module_path/CWRC-Writer/src/css/style.css" => array(),
      "$module_path/CWRC-Writer/src/css/islandora_style.css" => array(),
      "$module_path/CWRC-Writer/src/css/layout-default-latest.css" => array(),
      "$module_path/CWRC-Writer/src/js/lib/snippet/jquery.snippet.css" => array(),
      "$module_path/CWRC-Writer/src/smoothness/jquery-ui-1.10.4.custom.css" => array(),
      "$module_path/CWRC-Writer/src/js/lib/bootstrap/bootstrap.css" => array(),
      "$module_path/CWRC-Writer/src/js/cwrcDialogs/css/datepicker.css" => array(),
      "$module_path/CWRC-Writer/src/js/cwrcDialogs/css/cD.css" => array(),
    ),
  );
  return $items;
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_markup_editor_islandora_markupEditorCModel_islandora_view_object($object, $page_number, $page_size) {
  return theme('islandora_markup_editor', array('islandora_object' => $object));
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_markup_editor_islandora_markupEditorCModel_islandora_ingest_steps() {
  return array(
    'islandora_tei_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_markup_editor_tei_upload_form',
      'module' => 'islandora_markup_editor',
      'file' => 'includes/tei_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_markup_editor_islandora_markupeditorschemaCModel_islandora_ingest_steps() {
  return array(
    'islandora_schema_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_markup_editor_schema_upload_form',
      'module' => 'islandora_markup_editor',
      'file' => 'includes/schema_upload.form.inc',
    ),
  );
}

/**
 * Helper function to see if the user can save data.
 *
 * @param AbstractObject $object
 *   An AbstractObject representing an object within Fedora.
 *
 * @return bool
 *   TRUE if the user has access, FALSE otherwise.
 */
function islandora_markup_editor_save_tei_access(AbstractObject $object) {
  if (!isset($object['OBJ'])) {
    return FALSE;
  }
  return islandora_datastream_access(ISLANDORA_METADATA_EDIT, $object['OBJ']);
}
