<?php
/**
 * @file
 * Main hook implementations for islandora_plotit.
 */

/**
 * Implements hook_menu().
 */
function islandora_plotit_menu() {
  $items = array();

  $items['admin/islandora/search/islandora_solr/plotit'] = array(
    'title' => 'PlotIt',
    'description' => 'Configure Islandora PlotIt.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_plotit_admin_form'),
    'access arguments' => array('administer islandora solr'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora-bookmark/listid/%/plotit_json'] = array(
    'title' => 'JSON Output for bookmark list %id',
    'title arguments' => array('%id' => 2),
    'page callback' => 'islandora_plotit_bookmark_list_json',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_bookmark_access',
    'access arguments' => array(2),
    'file' => 'includes/bookmark-output.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora-bookmark/listid/%/plotit'] = array(
    'title' => 'View PlotIt',
    'page callback' => 'islandora_plotit_bookmark_plotit_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_bookmark_access',
    'access arguments' => array(2),
    'file' => 'includes/bookmark-output.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['islandora/object/%islandora_object/plotit'] = array(
    'title' => 'View PlotIt',
    'page callback' => 'islandora_plotit_collection_plotit_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_collection_access',
    'access arguments' => array(2),
    'file' => 'includes/collection-output.inc',
    'type' => MENU_LOCAL_TASK,
  );


  // 2015-10-07 - XML DB integrated versions
  // bookmark: main link to Plot-It given a list of bookmark items
  $items['islandora-bookmark/listid/%/plotit_xmldb'] = array(
    'title' => 'View PlotIt - XML DB',
    'page callback' => 'islandora_plotit_bookmark_plotit_xmldb_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_bookmark_access',
    'access arguments' => array(2),
    'file' => 'includes/bookmark-output.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  // bookmark: callback from the above menu items that produces the JSON 
  $items['islandora-bookmark/listid/%/plotit_xmldb_json'] = array(
    'title' => 'JSON Output for bookmark list %id',
    'title arguments' => array('%id' => 2),
    'page callback' => 'islandora_plotit_bookmark_list_xmldb_json',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_bookmark_access',
    'access arguments' => array(2),
    'file' => 'includes/bookmark-output.inc',
    'type' => MENU_CALLBACK,
  );
  // collection: callback from the above menu items that produces the JSON 
  $items['islandora-collection/object/%islandora_object/plotit_xmldb_json'] = array(
    'title' => 'JSON Output for collection %id',
    'title arguments' => array('%id' => 2),
    'page callback' => 'islandora_plotit_collection_plotit_xmldb_json',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_collection_access',
    'access arguments' => array(2),
    'file' => 'includes/collection-output.inc',
    'type' => MENU_CALLBACK,
  );
  $items['islandora/object/%islandora_object/plotit_xmldb'] = array(
    'title' => 'View PlotIt - XML DB',
    'page callback' => 'islandora_plotit_collection_plotit_xmldb_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_collection_access',
    'access arguments' => array(2),
    'file' => 'includes/collection-output.inc',
    'type' => MENU_CALLBACK,
  );


  // Voyant integration - Fedora Object 
  $items['islandora/object/%islandora_object/voyant'] = array(
    'title' => 'View Voyant',
    'page callback' => 'islandora_plotit_collection_voyant_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_collection_access',
    'access arguments' => array(2),
    'file' => 'includes/voyant_helpers.inc',
    'type' => MENU_CALLBACK,
  );
  // Voyant integration 
  // bookmark: callback from the  
  $items['islandora-bookmark/listid/%/voyant'] = array(
    'title' => 'Voyant content delimited by a bookmark list %id',
    'title arguments' => array('%id' => 2),
    'page callback' => 'islandora_plotit_bookmark_voyant_page',
    'page arguments' => array(2),
    'access callback' => 'islandora_plotit_bookmark_access',
    'access arguments' => array(2),
    'file' => 'includes/voyant_helpers.inc',
    'type' => MENU_CALLBACK,
  );



  return $items;
}


/**
 * Implements hook_cwrc_visualization_info().
 * 
 * Does so on behalf of the plotit module, the only visualization tool available
 * as of yet.
 * */
function islandora_plotit_cwrc_visualization_info() {

  global $base_url;

  $tools = array();

  $tools['plotit-2.0'] = array(
      'label' => 'PlotIt 2.0',
      'available cmodels' => array(
        'islandora:collectionCModel',
      ),
      'url pattern' => $base_url.'/islandora/object/%object_pid%/plotit_xmldb',
      'weight' => 10,
      'search display' => 'plotit',
      'search hide facets' => true,
      'bookmark path' => 'islandora-bookmark/listid/%list_id%/plotit_xmldb_json',
    
    );


  $tools['voyant'] = array(
      'label' => 'Voyant',
      'available cmodels' => array(
        'islandora:collectionCModel',
      ),
      'url pattern' => $base_url.'/islandora/object/%object_pid%/voyant',
      'weight' => 20,
      'search display' => 'voyant',
      'search hide facets' => true,
      'bookmark path' => 'islandora-bookmark/listid/%list_id%/voyant',
    
    );

  return $tools;
}




/**
 * Implements hook_islandora_solr_secondary_display().
 */
function islandora_plotit_islandora_solr_secondary_display() {
  return array(
    'plotit' => array(
      'name' => t('PlotIt'),
      'module' => 'islandora_plotit',
      'file' => 'includes/plotit_results.inc',
      'class' => 'IslandoraSolrResultsPlotit',
      'function' => 'printResults',
      'description' => t('Display PlotIt results.'),
      'logo' => t(
        '!span_startPlotIt!span_end',
        array(
          '!span_start' => '<span class="islandora-plotit-secondary-display">',
          '!span_end' => '</span>',
        )
      ),
    ),
    'plotit_json' => array(
      'name' => t('PlotIt JSON'),
      'module' => 'islandora_plotit',
      'file' => 'includes/json_results.inc',
      'class' => 'IslandoraSolrResultsPlotitJson',
      'function' => 'printResults',
      'description' => t('Display formatted PlotIt JSON results.'),
      'logo' => t(
        '!span_startPlotIt JSON!span_end',
        array(
          '!span_start' => '<span class="islandora-plotit-json-secondary-display">',
          '!span_end' => '</span>',
        )
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_plotit_theme() {
  $module_path = drupal_get_path('module', 'islandora_plotit');
  return array(
    'islandora_plotit_display_plotit' => array(
      'path' => "$module_path/theme",
      'file' => 'theme.inc',
      'template' => 'islandora-plotit-display-plotit',
      'variables' => array(
        'json_callback_url' => NULL,
      ),
    ),
  );
}

/**
 * Access callback for collection PlotIt view.
 */
function islandora_plotit_collection_access(AbstractObject $object) {
  return islandora_object_access(ISLANDORA_VIEW_OBJECTS, $object) && in_array('islandora:collectionCModel', $object->models);
}

/**
 * Wrap access callback, if bookmark is not enabled.
 */
function islandora_plotit_bookmark_access($list_id) {
  return module_exists('islandora_bookmark') && islandora_bookmark_access($list_id);
}
